spring:
  mail:
    host: smtp.gmail.com # 1
    port: 587 # 2
    username: spoonmap.ad@gmail.com
    password: spoonmap123!!
    properties:
      mail:
        smtp:
          auth: true # 5
          timeout: 5000 # 6
          starttls:
            enable: true # 7

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://spoonmap.cdryf41hmarv.ap-northeast-2.rds.amazonaws.com:3306/spoonmap?serverTimezone=Asia/Seoul
    username: dev
    password: test123

  jpa:
    show_sql: true
    properties:
      hibernate:
        format_sql: true

decorator:
  datasource:
    p6spy:
      enable-logging: true
