name: CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ 'feature/**', 'refactor/**', 'fix/**', 'chore/**' ]

jobs:
  CI-CD:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      ## JDK 17 set up
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      ## application properties
      - name: make application.yml
        run: |
          cd ./src/main/resources
          touch ./application.yml
          echo "${{ secrets.PROPERTIES }}" > ./application.yml
        shell: bash
      ## application properties for test
      - name: make application.yml for test
        run: |
          cd ./src/test
          mkdir resources && cd resources
          touch ./application.yml
          echo "${{ secrets.TEST_PROPERTIES }}" > ./application.yml
        shell: bash
      # Gradle build
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build
      # below steps work only for main branch
      # docker build & push image to registry

      - name: Get Github Actions IP
        if: contains(github.ref, 'main')
        id: ip
        uses: haythem/public-ip@v1.2

      - name: Configure AWS Credentials
        if: contains(github.ref, 'main')
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Add Github Actions IP to Security group
        if: contains(github.ref, 'main')
        run: |
          aws ec2 authorize-security-group-ingress --group-id ${{ secrets.AWS_SG_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32

      - name: Docker build & push to registry
        if: contains(github.ref, 'main')
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_REPO }}/spoonmap .
          docker push ${{ secrets.DOCKER_REPO }}/spoonmap
      ## deploy to aws ec2
      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@master
        if: contains(github.ref, 'main')
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            docker-compose down
            docker rm -f $(docker ps -qa)
            docker rmi -f ${{ secrets.DOCKER_REPO }}/spoonmap
            docker-compose up -d

      - name: Remove Github Actions IP From Security Group
        if: contains(github.ref, 'main')
        run: |
          aws ec2 revoke-security-group-ingress --group-id ${{ secrets.AWS_SG_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32
